export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const FETCH_EXPENSE = 'FETCH_EXPENSE';
export const LISTEN_TO_EXPENSES_MONTH = 'LISTEN_TO_EXPENSES_MONTH';
export const LISTEN_TO_EXPENSES_YEAR = 'LISTEN_TO_EXPENSES_YEAR';
export const LISTEN_TO_EXPENSES_CUSTOM_DATES = 'LISTEN_TO_EXPENSES_CUSTOM_DATES';

